blank_issues_enabled: false
contact_links:
  - name: amazon-orders Community Support
    url: https://github.com/alexdlaird/amazon-orders/discussions
    about: Please put integration questions and suggestions here.