name: Integration Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  test:
    name: Integration Test

    env:
      FORCE_COLOR: 1
      AMAZON_USERNAME: ${{ secrets.AMAZON_USERNAME }}
      AMAZON_PASSWORD: ${{ secrets.AMAZON_PASSWORD }}
      AMAZON_OTP_SECRET_KEY: ${{ secrets.AMAZON_OTP_SECRET_KEY }}
      # The following variables are not required, defaults will be used if they are not defined
      AMAZON_BASE_URL: ${{ vars.AMAZON_BASE_URL }}
      AMAZON_INTEGRATION_TEST_AUTH_WRONG_PASSWORD: ${{ vars.AMAZON_INTEGRATION_TEST_AUTH_WRONG_PASSWORD }}
      AMAZON_INTEGRATION_TEST_YEAR: ${{ vars.AMAZON_INTEGRATION_TEST_YEAR }}
      AMAZON_START_INDEX: ${{ vars.AMAZON_START_INDEX }}
      AMAZON_TRANSACTIONS_DAYS: ${{ vars.AMAZON_TRANSACTIONS_DAYS }}
      AMAZON_FULL_DETAILS_LOOP_COUNT: ${{ vars.AMAZON_FULL_DETAILS_LOOP_COUNT }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install jpeg
        run: sudo apt-get install -y libjpeg-dev zlib1g-dev
      - name: Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_wait_seconds: 300
          max_attempts: 3
          command: make test-integration