name: Integration Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 1"

jobs:
  test:
    name: Integration Test

    env:
      AMAZON_USERNAME: ${{ secrets.AMAZON_USERNAME }}
      AMAZON_PASSWORD: ${{ secrets.AMAZON_PASSWORD }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      TO_PHONE_NUMBER: ${{ secrets.TO_PHONE_NUMBER }}
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 300
          max_attempts: 3
          command: make install test-integration