name: Integration Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  test:
    name: Integration Test

    env:
      FORCE_COLOR: 1
      AMAZON_USERNAME: ${{ secrets.AMAZON_USERNAME }}
      AMAZON_PASSWORD: ${{ secrets.AMAZON_PASSWORD }}
      OTP_SECRET_KEY: ${{ secrets.OTP_SECRET_KEY }}
      INTEGRATION_TEST_FULL_DETAILS_LOOP_COUNT: ${{ vars.INTEGRATION_TEST_FULL_DETAILS_LOOP_COUNT }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install jpeg
        run: sudo apt-get install -y libjpeg-dev zlib1g-dev
      - name: Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 300
          max_attempts: 3
          command: USE_TINY_SERVER=True make test-integration